# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.26

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/master/viper/midas

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/master/viper/midas

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/master/viper/midas/CMakeFiles /home/master/viper/midas//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/master/viper/midas/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named midas

# Build rule for target.
midas: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 midas
.PHONY : midas

# fast build rule for target.
midas/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/midas.dir/build.make CMakeFiles/midas.dir/build
.PHONY : midas/fast

CMakeFiles/3.26.4/CompilerIdCXX/CMakeCXXCompilerId.o: CMakeFiles/3.26.4/CompilerIdCXX/CMakeCXXCompilerId.cpp.o
.PHONY : CMakeFiles/3.26.4/CompilerIdCXX/CMakeCXXCompilerId.o

# target to build an object file
CMakeFiles/3.26.4/CompilerIdCXX/CMakeCXXCompilerId.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/midas.dir/build.make CMakeFiles/midas.dir/CMakeFiles/3.26.4/CompilerIdCXX/CMakeCXXCompilerId.cpp.o
.PHONY : CMakeFiles/3.26.4/CompilerIdCXX/CMakeCXXCompilerId.cpp.o

CMakeFiles/3.26.4/CompilerIdCXX/CMakeCXXCompilerId.i: CMakeFiles/3.26.4/CompilerIdCXX/CMakeCXXCompilerId.cpp.i
.PHONY : CMakeFiles/3.26.4/CompilerIdCXX/CMakeCXXCompilerId.i

# target to preprocess a source file
CMakeFiles/3.26.4/CompilerIdCXX/CMakeCXXCompilerId.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/midas.dir/build.make CMakeFiles/midas.dir/CMakeFiles/3.26.4/CompilerIdCXX/CMakeCXXCompilerId.cpp.i
.PHONY : CMakeFiles/3.26.4/CompilerIdCXX/CMakeCXXCompilerId.cpp.i

CMakeFiles/3.26.4/CompilerIdCXX/CMakeCXXCompilerId.s: CMakeFiles/3.26.4/CompilerIdCXX/CMakeCXXCompilerId.cpp.s
.PHONY : CMakeFiles/3.26.4/CompilerIdCXX/CMakeCXXCompilerId.s

# target to generate assembly for a file
CMakeFiles/3.26.4/CompilerIdCXX/CMakeCXXCompilerId.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/midas.dir/build.make CMakeFiles/midas.dir/CMakeFiles/3.26.4/CompilerIdCXX/CMakeCXXCompilerId.cpp.s
.PHONY : CMakeFiles/3.26.4/CompilerIdCXX/CMakeCXXCompilerId.cpp.s

src/IR/Function.o: src/IR/Function.cpp.o
.PHONY : src/IR/Function.o

# target to build an object file
src/IR/Function.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/midas.dir/build.make CMakeFiles/midas.dir/src/IR/Function.cpp.o
.PHONY : src/IR/Function.cpp.o

src/IR/Function.i: src/IR/Function.cpp.i
.PHONY : src/IR/Function.i

# target to preprocess a source file
src/IR/Function.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/midas.dir/build.make CMakeFiles/midas.dir/src/IR/Function.cpp.i
.PHONY : src/IR/Function.cpp.i

src/IR/Function.s: src/IR/Function.cpp.s
.PHONY : src/IR/Function.s

# target to generate assembly for a file
src/IR/Function.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/midas.dir/build.make CMakeFiles/midas.dir/src/IR/Function.cpp.s
.PHONY : src/IR/Function.cpp.s

src/Module.o: src/Module.cpp.o
.PHONY : src/Module.o

# target to build an object file
src/Module.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/midas.dir/build.make CMakeFiles/midas.dir/src/Module.cpp.o
.PHONY : src/Module.cpp.o

src/Module.i: src/Module.cpp.i
.PHONY : src/Module.i

# target to preprocess a source file
src/Module.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/midas.dir/build.make CMakeFiles/midas.dir/src/Module.cpp.i
.PHONY : src/Module.cpp.i

src/Module.s: src/Module.cpp.s
.PHONY : src/Module.s

# target to generate assembly for a file
src/Module.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/midas.dir/build.make CMakeFiles/midas.dir/src/Module.cpp.s
.PHONY : src/Module.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... midas"
	@echo "... CMakeFiles/3.26.4/CompilerIdCXX/CMakeCXXCompilerId.o"
	@echo "... CMakeFiles/3.26.4/CompilerIdCXX/CMakeCXXCompilerId.i"
	@echo "... CMakeFiles/3.26.4/CompilerIdCXX/CMakeCXXCompilerId.s"
	@echo "... src/IR/Function.o"
	@echo "... src/IR/Function.i"
	@echo "... src/IR/Function.s"
	@echo "... src/Module.o"
	@echo "... src/Module.i"
	@echo "... src/Module.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

